# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        village:
            quality: 75
            filters:
                thumbnail:
                    size: [350,250]
                    mode: outbound

        imagecandidat:
            quality: 75
            filters:
                thumbnail:
                    size: [350,250]
                    mode: outbound

        imagecandidat_vote:
            quality: 75
            filters:
                thumbnail:
                    size: [50,50]
                    mode: outbound
        imagecandidat_admin:
            quality: 75
            filters:
                thumbnail:
                    size: [100,75]
                    mode: outbound
        president_admin:
            quality: 75
            filters:
                thumbnail:
                    size: [100,75]
                    mode: outbound 
        utilisateur_admin:
            quality: 75
            filters:
                thumbnail:
                    size: [100,75]
                    mode: outbound

        article:
            quality: 75
            filters:
                scale:
                    dim: [350,200]